### ISSUE TITLE
Can DeltaCNN be deployed with tensorrt, or is there any other way

### ISSUE THREAD

**Issue by jiaerwang0328** [dabeschte/DeltaCNN#5]
I am trying to deploy my models with  DeltaCNN,but I don't know how to start,. I am wondering if there is any easier way for deploying models such that I could directly utilize c++ for fast inference? could you give me some advice?  Thanks in advance.

**Comment by dabeschte** [comment]
Unfortunately, I haven't used TensorRT yet and therefore can't really tell how to integrate custom kernels together with custom buffers. But if you implement an integration, please consider to open source it, because that would be very helpful for a lot of people.

Regarding using DeltaCNN in C++, this should not be too difficult.
Specific layers used in PyTorch are implemented in sparse_layers.py. They are responsible for allocating buffers, storing/requesting thresholds and for calling the requested cuda kernels. All calls to sparse DeltaCNN kernels go though 2 stages: 
- cuda_kernels.py: allocates output tensors and calls c++ wrapper functions. This file could also be stripped away and merged with sparse_layers.py or conv_torch_wrapper.cpp, but it was a very helpful intermediate layer for debugging and profiling.
- conv_torch_wrapper.cpp: this file does some sanity checks on the input parameters and converts all inputs to float/half pointers before calling the specific cuda kernel launchers. (conv_kernel.cu, deconv_kernel.cu, other_nn_layers.cu).

All cuda kernels are then independent of the ML framework and should not require any custom adaptions.

The steps required for DeltaCNN in another framework/C++ are:
- port sparse_layers.py to be compatible with the desired framework's layer architecture. Allocate required buffers for each layer in the correct shape and access the thresholds used for truncation.
- port conv_torch_wrapper.cpp: as the main purpose of this file is to get data pointers from tensors and then run the actual kernels, you might be able to skip this file
- port cuda_kernels.py: as the main purpose of this file is to allocate output and call conv_torch_wrapper.cpp, you should be able to easily integrate it into your sparse_layer.py port.

What you also need to consider is that DeltaCNN uses a special format to store the weights for efficient access. You either need to port filter_conversion.py as well, or just export the weights from PyTorch after conversion.

**Comment by jiaerwang0328** [comment]
> 
Thanks for the  reply！
